config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root 'requests#index'
  resources :requests do
    resources :answers do
      resource :favorites, only: %i[create destroy]
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
  belongs_to :request
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @answer = Answer.find(params[:answer_id])
    @answer_favorite = Favorite.new(user_id: current_user.id, answer_id: params[:answer_id],
                                    request_id: params[:request_id])
    @answer_favorite.save
  end

  def destroy
    @answer = Answer.find(params[:answer_id])
    @answer_favorite = Favorite.find_by(user_id: current_user.id, answer_id: params[:answer_id],
                                        request_id: params[:request_id])
    @answer_favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if answer.favorited?(current_user) %>
  <%= link_to request_answer_favorites_path(request_id: answer.request_id, answer_id:answer.id), method: :delete, remote: :true do %>
    <i class="fa fa-heart unfavorite-btn"> いいね</i>
  <% end %>  
<% else %>
  <%= link_to request_answer_favorites_path(request_id: answer.request_id, answer_id:answer.id), method: :post, remote: :true do %>
    <i class="fa fa-heart favorite-btn"> いいね</i>
  <% end %>
<% end %>        

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @answer.id %>').html("<%= j(render "favorites/favorite", answer: @answer)%>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @answer.id %>').html("<%= j(render "favorites/favorite", answer: @answer)%>");