config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root 'requests#index'
  resources :requests do
    resources :answers do
      resource :favorites, only: %i[create destroy]
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="top-page-header">
<link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
  <div class="header-contents">
    <%= link_to 'FashionApp', "/", class:"header-title"%>
  </div>  
  <div class="nav">
    <ul class="nav-lists">
      <% if user_signed_in? %>
      <li><%= link_to 'リクエスト投稿', new_request_path, class:"request-post", id:"request-post"%>
      <li><%= link_to current_user.nickname, edit_user_registration_path, class: "user-nickname", id:"user-nickname" %>
      <li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "logout", id:"logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login", id:"login" %></li>
      <li><%= link_to '新規登録',new_user_registration_path, class: "sign-up", id:"signup" %></li>
      <% end %>
    </ul>
  </div>
</header>