config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root 'requests#index'
  resources :requests do
    resources :answers do
      resource :favorites, only: %i[create destroy]
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
  validates :sex_id, numericality: { other_than: 1, message: "can't be blank" }
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_request, only: %i[edit update destroy]
  def index
    @requests = Request.all
    @answers = Answer.all
  end

  def new
    @request = Request.new
  end

  def edit; end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @request.update(request_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @request.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:sex_id, :text).merge(user_id: current_user.id)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<%= render "shared/header"%>
<%=image_tag 'main-image.png', class:'background-image'%>
<link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
<div class="edit-form-wrap">
  <%= form_with model: @request, url: request_path, id: 'edit_request', class: 'edit_request', local: true  do |f| %>
    <div class="weight-bold-text">性別</div>
     <div class="field">
       <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"sex"} )%>
     </div>
    <div class="field">
      <%= f.label :text %><br />
      <%= f.text_field :text, class:"input-field", autofocus: true, autocomplete: "nickname" %>
    </div>
    <div class="actions">
      <%= f.submit "Update", class:"submit-button"%>
    </div>
  <% end %>
</div>  

app/views/requests/index.html.erb
<div class='start'>
  <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
  <p>FashionApp</p>
</div>  

<%= render "shared/header"%>
<div class='main'>
  <%= image_tag 'main-image.png', class:"main-image" %>
  <div class='title-contents'>
    <h2 class='service-title' id='service-title'>
      あなたを着飾る一着を
    </h2>  
  </div>
  <div class="answered-request" id="answerModal">
    <div class="answer-request-info">回答済み質問一覧</div>
    <div class="close-btn" id="closeModal2">✖︎</div>
      <% @answers.each do |answer| %>
        <div class="answer-request-content">
          <div class="answer-request-nickname">
            質問者名:
            <%= answer.request.user.nickname%>
          </div>
          <div class="answer-request-text">
            質問内容:<br>
            <%= answer.request.text %>
          </div>
          <div class="answer-content">
            <div class="answer-content-title">回答内容</div>
            <%= image_tag answer.image.variant(resize: '200x200') ,class:"answer-img"%>
            <div class="answer-text">
              回答:
              <%= answer.text %>
            </div>
            <% if user_signed_in? && current_user.id != answer.user_id %>
            <div id="favorites_buttons_<%= answer.id %>">
              <%= render  'favorites/favorite', answer: answer %>
            </div>
            <% end %>
            <% if user_signed_in? && current_user.id == answer.user_id %>
              <%= link_to '編集', edit_request_answer_path(answer.request.id, answer.id), class:"edit-btn" %>
              <%= link_to '削除', request_answer_path(answer.request.id, answer.id), class:"delete-btn", method: :delete %>
            <% end %>  
          </div>  
        </div>   
      <% end %>  
  </div>
  <div class="request-btn" id="openModal">リクエストを表示</div>
  <div class="answered-request-btn" id="openModal2">回答済みの質問を表示</div>
  <div class="request-view" id="request-modal">
    <div class="close-btn" id="closeModal">✖︎</div>
    <% @requests.each do |request| %>
      <div class="request-info">
        <div class="request-user">
          ユーザー名: 
          <%= request.user.nickname %>
        </div>  
        <div class="sex">
          性別：
          <%= request.sex.name %>
        </div>
        <div class="height">
          身長:
          <%= request.user.height %>cm
        <div class="request-text">
          質問内容:
          <%= request.text %>
        </div>
        <div class="btn-group">
          <% if user_signed_in? && current_user.id == request.user_id %>
            <%= link_to '編集',  edit_request_path(request.id), class:"edit-btn" %>
            <%= link_to '削除', request_path(request.id), class:"delete-btn", method: :delete %>
          <% end %>
          <% if user_signed_in? && current_user.id != request.user_id %>
            <%= link_to '回答する', new_request_answer_path(request.id), class:"answer-btn" %>
          <% end %>
        </div>
      </div>   
    <% end %>
  </div>
</div>

app/views/requests/new.html.erb
<%= render "shared/header"%>
<div class="requests-main">
  <%=image_tag 'main-image.png', class:'new-image'%>
  <div class="requests">
    <h2 class="requests-form-title">リクエスト情報を入力</h2>
    <div class="form"> 
      <%= form_with model: @request, class:"requests-form",local:true do |f| %>
        <%= render "shared/error_messages", model: f.object, resource: @request %>
        <div class="weight-bold-text">性別</div>
        <div class="field">
          <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"sex"} )%>
        </div>
        <div class="weight-bold-text">本文</div>
        <div class="field">
          <%= f.text_area :text, class:"text-form", id:"requests-text" %>
        </div>
        <div class="action">
          <div class="post-btn">
          <%= f.submit "送信する", class:"post-btn"%>
        </div>
      <% end %>
    </div>  
  </div>
</div>